### ISSUE TITLE
Run other file extensions

### ISSUE THREAD

**Issue by tuckerzp** [showalter/bdws#12]
Worker assumes all jobs are bash. That should change

**Comment by showalter** [comment]
So, here's what we should plan to do with this.

Currently, the client sends a **single** file over (we're going to limit these initial versions to a single file, we may branch out to multiple files in an archive later, and certainly not until after the mid-project deliverable). So, we have the name and extension. We should naively trust that the user uses a proper extension for the type of file they're sending.

We should build some sort of mapping for how to take a single file and run it, and put as an intermediary step before running the code.

| *filename.extension* | Steps to execute |
| ---------------------- | ------------------- |
| *Classname*.java       | `javac *Classname*.java`, `java *Classname*` |
| *Classname*.class      | `java *Classname*` |
| *archive*.jar               | `java -jar *archive*.jar` |
| *name*.py                 | `python3 *name*.py` |
| *name*.sh                 | `./*name*.sh` |
| *name* (no extension) | `./*name*` |

And you can imagine how this list can grow to be huge, but it certainly doesn't need to be exhaustive at the moment. Including these for now would be plenty, especially if we have a good system in place for adding more.
