### ISSUE TITLE
Fix worker paralyzing system 

### ISSUE THREAD

**Issue by tuckerzp** [showalter/bdws#23]
Dr Lam: "Also, I tried **killing one of the workers and it seems to paralyze the entire system** (i.e., nothing succeeds after that, even partially), which I guess makes sense if you haven't really done any fault tolerance work yet. Honestly, I think having some really robust functionality in this area would be more interesting than doing a super-extensive performance analysis"

**Comment by tuckerzp** [comment]
@showalter I added you too because you are more familiar with worker sign up than I am

**Comment by showalter** [comment]
What's happening here isn't really with worker registration. I think this would be something that we'd be able to at least mostly solve with a robust solution for #16. What happens is that the supervisor tries to contact the worker and it can't, so our current behavior is to panic. Easy fix, don't panic.
