### ISSUE TITLE
java files fail (INVALID)

### ISSUE THREAD

**Issue by tuckerzp** [showalter/bdws#36]
running ./client {hostname} {javafile} causes workers to go in infinite loop like #31 

The program should just work in general. This is most likely a problem with java being finicky with args

**Comment by showalter** [comment]
This is not a great issue description. We need more detail on what the issue is, what causes it, and what we can do to fix it.

**Comment by tuckerzp** [comment]
> This is not a great issue description. We need more detail on what the issue is, what causes it, and what we can do to fix it.

Updated

**Comment by tuckerzp** [comment]
Upon messing around with it a bit more:

The intended functionality is: if you have a Test.java file on worker 5021, i would compile and run **java -cp 5021 Test**

Printing out the args found that they **are** [-cp 5021 Test] 

So I am unsure what might be causing issue

**Comment by tuckerzp** [comment]
I am sorry :sob:
